version: '3.7'
services:
  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana_storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - observability-network


  tempo:
    image: grafana/tempo:2.2.0
    command: ["--config.file=/etc/tempo-local.yaml"]
    ports:
      - 3200:3200
    volumes:
      - ./tempo/tempo-local.yaml:/etc/tempo-local.yaml
    depends_on:
      - loki
    networks:
      - observability-network

  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
    networks:
      - observability-network

  pushgateway:
    image: prom/pushgateway:v1.6.2
    ports:
      - 9091:9091
    networks:
        - observability-network

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - 3100:3100  
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml 
    networks:
      - observability-network
      
volumes:
  grafana_storage:

networks:
  observability-network:
    driver: bridge 